<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZfThemes\Module'                        => __DIR__ . '/Module.php',
    'ZfThemes\Controller\ZfthemeController' => __DIR__ . '/src/ZfThemes/Controller/ZfthemeController.php',
    'ZfThemesTest\Framework\TestCase'        => __DIR__ . '/tests/ZfThemes/Framework/TestCase.php',
    'ZfThemesTest\SampleTest'                => __DIR__ . '/tests/ZfThemes/SampleTest.php',
);
